apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-service-indian-store
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-service-indian-store
  template:
    metadata:
      labels:
        app: mcp-service-indian-store
    spec:
      containers:
        - name: indian-store-mcp
          image: ghcr.io/vishalk17/indian-store-mcp-server:0.005
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-service-indian-store
  namespace: default
spec:
  selector:
    app: mcp-service-indian-store
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
