apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: mcp-service-indian-store-gatewayclass
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mcp-service-indian-store-gateway
  namespace: default
spec:
  gatewayClassName: mcp-service-indian-store-gatewayclass
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-cloudwithme-dev-tls
      allowedRoutes:
        namespaces:
          from: All
---
# MCP Server
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-route
  namespace: default
spec:
  parentRefs:
    - name: mcp-service-indian-store-gateway
  hostnames:
    - "vishalk17.cloudwithme.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: mcp-service-indian-store
          port: 80
---
# Hydra OAuth2 (public endpoints)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hydra-public-route
  namespace: default
spec:
  parentRefs:
    - name: mcp-service-indian-store-gateway
  hostnames:
    - "vishalk17.cloudwithme.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /oauth2
      backendRefs:
        - name: hydra-public
          port: 4444
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known
      backendRefs:
        - name: hydra-public
          port: 4444
---
# Kratos (auth flows)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kratos-route
  namespace: default
spec:
  parentRefs:
    - name: mcp-service-indian-store-gateway
  hostnames:
    - "vishalk17.cloudwithme.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /kratos
      backendRefs:
        - name: kratos-public
          port: 80
---
# Kratos UI (login interface)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kratos-ui-route
  namespace: default
spec:
  parentRefs:
    - name: mcp-service-indian-store-gateway
  hostnames:
    - "vishalk17.cloudwithme.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: kratos-selfservice-ui-node
          port: 3000
