kratos:
  config:
    dsn: postgres://ory:changeme@postgres-postgresql:5432/kratos?sslmode=disable
    
    serve:
      public:
        base_url: https://vishalk17.cloudwithme.dev/kratos
        cors:
          enabled: true
      admin:
        base_url: http://kratos-admin:4434
    
    selfservice:
      default_browser_return_url: https://vishalk17.cloudwithme.dev/
      allowed_return_urls:
        - https://vishalk17.cloudwithme.dev
      
      methods:
        password:
          enabled: false
        oidc:
          enabled: true
          config:
            providers:
              - id: github
                provider: github
                client_id: Ov23lihfWwAoEOnpddJ2
                client_secret: 0d3d552078488c3eb262fb3a562123f81b6aef09
                mapper_url: base64://bG9jYWw6Ly90cmFpdHMuZW1haWwgPSBjbGFpbXMuZW1haWw=
                scope:
                  - user:email
              
              - id: microsoft
                provider: microsoft
                client_id: cdeefe35-06ad-4334-a074-0c91d70fc6f1
                client_secret: wwe8Q~dQTuWgBQpB8zH52TstzjVw--gAZmN2RbLB
                mapper_url: base64://bG9jYWw6Ly90cmFpdHMuZW1haWwgPSBjbGFpbXMuZW1haWw=
                microsoft_tenant: common
                scope:
                  - email
              
              - id: google
                provider: google
                client_id: YOUR_GOOGLE_CLIENT_ID
                client_secret: YOUR_GOOGLE_CLIENT_SECRET
                mapper_url: base64://bG9jYWw6Ly90cmFpdHMuZW1haWwgPSBjbGFpbXMuZW1haWw=
                scope:
                  - email
                  - profile
      
      flows:
        error:
          ui_url: https://vishalk17.cloudwithme.dev/auth/error
        
        settings:
          ui_url: https://vishalk17.cloudwithme.dev/auth/settings
        
        recovery:
          enabled: false
        
        verification:
          enabled: false
        
        logout:
          after:
            default_browser_return_url: https://vishalk17.cloudwithme.dev/auth/login
        
        login:
          ui_url: https://vishalk17.cloudwithme.dev/auth/login
          after:
            default_browser_return_url: https://vishalk17.cloudwithme.dev/
          lifespan: 10m
        
        registration:
          enabled: false
          ui_url: https://vishalk17.cloudwithme.dev/auth/registration
    
    secrets:
      cookie:
        - 8a00db2429194ca8cb56a72c272ed710
      cipher:
        - 57237739d95f8a41968455be1a1c5302
    
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9zY2hlbWFzLm9yeS5zaC9wcmVzZXRzL2tyYXRvcy9pZGVudGl0eS5lbWFpbC5zY2hlbWEuanNvbiIsCiAgIiR0aXRsZSI6ICJQZXJzb24iLAogICJ0eXBlIjogIm9iamVjdCIsCiAgInByb3BlcnRpZXMiOiB7CiAgICAidHJhaXRzIjogewogICAgICAidHlwZSI6ICJvYmplY3QiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiZW1haWwiOiB7CiAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgImZvcm1hdCI6ICJlbWFpbCIKICAgICAgICB9CiAgICAgIH0sCiAgICAgICJyZXF1aXJlZCI6IFsiZW1haWwiXQogICAgfQogIH0KfQ==
  
  automigration:
    enabled: true

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
